<?php

namespace CursusBundle\Repository;

/**
 * CursusTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursusTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
