<?php

namespace CursusBundle\Repository;

/**
 * CursusRegistrationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursusRegistrationsRepository extends \Doctrine\ORM\EntityRepository
{
}
