<?php

namespace CursusBundle\Repository;

/**
 * OntwerpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OntwerpRepository extends \Doctrine\ORM\EntityRepository
{
}
