<?php

namespace CursusBundle\Repository;

/**
 * SchipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchipRepository extends \Doctrine\ORM\EntityRepository
{
}
