<?php

namespace AppBundle\Repository;

/**
 * ElectraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectraRepository extends \Doctrine\ORM\EntityRepository
{
}
